### ISSUE TITLE
Data labels are not always visible

### ISSUE THREAD

**Issue by globau** [Remimstr/COVID-19-globeview#1] opened 2020-03-15 09:37 UTC
Unless the point is in the centre of the viewport, data labels are quite often not visible.

Steps to reproduce:
1. Align the globe so the equator is vertically centred
2. Try to view the data for an Australian city

Expected:
- data labels should always be completely visible

Actual:
<img width="706" alt="Screenshot 2020-03-15 17 35 31" src="https://user-images.githubusercontent.com/872825/76698991-9adcea80-66e3-11ea-93d7-7ccfa781d224.png">

**Comment by hugetiny** [comment] 2020-03-15 14:39
This problem is caused by echarts.
I think disable the tooltips and manually shows a pop-up could be a solution for this.

**Comment by Remimstr** [comment] 2020-03-15 14:47
@hugetiny I actually tried that in an earlier build but I ran into an even worse bug where the whole chart would glitch out when I ran setOption with the new options. I'll make a new branch to show you what I mean.

**Comment by Remimstr** [comment] 2020-03-15 15:00
@hugetiny Actually I don't know what I'm talking about, it's just a hover event, there's no need to set any options... I'll make a new branch for this

**Comment by hugetiny** [comment] 2020-03-15 15:49
I found my solution.Tomorrow I will make a pr
the event should be 'mousemove'

**Comment by Remimstr** [comment] 2020-03-16 03:56
Hey @hugetiny, I already implemented a fix for this issue 89b3ed6a18008f104acb8441bcb9b91d71605bc0
I'm sorry if you really wanted to do it, I just really wanted to get rid of the broken tooltips as quickly as I could.

**Closed by Remimstr** 2020-03-16 03:56 UTC
Labels: bug

**Comment by hugetiny** [comment] 2020-03-16 09:47
@Remimstr It's OK.I will continously improve this project.
